In [1]:
import torch as t
%matplotlib notebook
import numpy as np
import myUtils
from matplotlib import pyplot as plt
from IPython import display

device = t.device('cpu')

In [3]:
t.manual_seed(2021)

In [4]:
def get_fake_data(batch_size):
    x = t.rand(batch_size,1,device = device)*5
    y = x*2+3+t.randn(batch_size,1,device=device)
    return x,y    

In [5]:
x,y = get_fake_data(batch_size = 16)


### autograd

In [7]:
import torch as t
a = t.randn(3,4,requires_grad = True)
a.requires_grad

True

In [9]:
a = t.randn(3,4)
a.requires_grad = True

In [16]:
b = t.zeros(3,4).requires_grad_()
c = (2*a+b).sum()
c.backward()
c

tensor(10.0827, grad_fn=<SumBackward0>)

In [17]:
a.grad

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [20]:
a.is_leaf,b.is_leaf,c.is_leaf

(True, True, False)

In [28]:
def f(x):
    y = x**2*t.exp(x)
    return y


In [40]:
x = t.randn(3,4,requires_grad = True)
y = f(x)
y

tensor([[3.3164e-01, 3.1586e-01, 2.3801e-02, 9.2090e-01],
        [3.6269e-01, 4.9090e-01, 3.0666e+01, 5.4929e-03],
        [5.6137e-01, 3.7085e-01, 2.8261e+00, 1.0967e+00]],
       grad_fn=<MulBackward0>)

In [41]:
y.backward(t.ones(y.size()))
x.grad


tensor([[ 1.7798, -0.4128, -0.2599,  3.6204],
        [-0.3730, -0.1919, 61.0521,  0.1591],
        [ 2.5489, -0.3649,  8.4056,  4.1106]])

In [2]:
import torch as t
%matplotlib inline
import numpy as np
import myUtils
import matplotlib.pyplot as plt
from IPython import display

device = t.device('cpu')

In [12]:
import torch as t
x = t.ones(1)
b = t.rand(1,requires_grad = True)
w = t.rand(1,requires_grad = True)
y = w*x
y.retain_grad()#保存非葉子節點的梯度
z = y+b

In [13]:
y.requires_grad

True

In [14]:
y.grad_fn
z.backward()

In [15]:
y.grad

tensor([1.])

In [16]:
x.grad_fn==None

True

In [17]:
with t.no_grad():#不保存梯度
    tq = z**2

tq.requires_grad

False

In [18]:
y1 = y.detach()
#y1不可導,且y1是葉節點
y1,y,y1.is_leaf

(tensor([0.8501]), tensor([0.8501], grad_fn=<MulBackward0>), True)

In [19]:
A = t.arange(1,5).reshape(2,2).float()
A

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
import torch as t
%matplotlib inline
import numpy as np
import myUtils
import matplotlib.pyplot as plt
from IPython import display

device = t.device('cpu')
plt.plot(1,2,'o')
plt.show()